import { create } from "zustand";

export const jumpRopeDefaultState = {
  jumpCount: 0,
  cadence: 0,
  bodyLean: 0,
  isJumping: false,
  cameraReady: false,
  detectionActive: false,
};

export const useGameStore = create((set) => ({
  playerPosition: null,
  setPlayerPosition: (position) => set({ playerPosition: position }),
  speed: null,
  setSpeed: (speed) => set({ speed: speed }),
  flamePositions: null,
  setFlamePositions: (positions) => set({ flamePositions: positions }),
  boostPower: 0,
  setBoostPower: (power) => set({ boostPower: power }),
  isBoosting : false,
  setIsBoosting: (isBoosting) => set({ isBoosting }),
  driftLevel: null,
  setDriftLevel: (level) => set({ driftLevel: level }),
  groundPosition: null,
  setGroundPosition: (groundPosition) => set({groundPosition: groundPosition}),
  wheelPositions: null,
  setWheelPositions: (wheelPositions) => set({wheelPositions: wheelPositions}),
  body: null,
  setBody: (body) => set({body: body}),
  joystick: {x: 0, y: 0, distance: 0},
  setJoystick: (joystick) => set({ joystick: joystick }),
  jumpButtonPressed: false,
  setJumpButtonPressed: (pressed) => set({ jumpButtonPressed: pressed }),
  noiseTexture: null,
  setNoiseTexture: (noiseTexture) => set({noiseTexture: noiseTexture}),
  gamepad: null,
  setGamepad: (gamepad) => set({gamepad: gamepad}),
  isOnDirt:null,
  setIsOnDirt: (isOnDirt) => set({isOnDirt: isOnDirt}),
  // Collision system
  collider: null,
  setCollider: (collider) => set({ collider }),
  trackScene: null,
  setTrackScene: (trackScene) => set({ trackScene }),
  // Jump rope controls
  jumpRope: { ...jumpRopeDefaultState },
  setJumpRope: (data) => set((state) => ({ jumpRope: { ...state.jumpRope, ...data } })),
  gameMode: null,
  setGameMode: (mode) => set({ gameMode: mode }),
  // Processed jump rope controls for the game
  jumpRopeControls: { forward: 0, steer: 0, driftActive: false },
  setJumpRopeControls: (controls) => set({ jumpRopeControls: controls }),
  cameraStream: null,
  setCameraStream: (stream) => set({ cameraStream: stream }),
}));
